const customers = [
    {
      id: "1111",
      companyName: "Taj Hotel",
      typeOfCompany: "Restaurant",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Active",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "Cheque",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales Person Name",
      salesPersonId: "SP123",
      carsPermittedPerDay: 50,
      packageType: "Standard",
      driversAllowed: 100,
      carsAllowedPerBranch: 20,
      driversAllowedPerBranch: 10,
      branchesAllowed: 5,
      primaryContactAndCompanyManagerSame: "Y",
    },
    {
      id: "1112",
      companyName: "Cheers Bar",
      typeOfCompany: "Bar",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Active",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "Cash",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales Person Name",
      salesPersonId: "SP123",
      carsPermittedPerDay: 50,
      packageType: "Standard",
      driversAllowed: 100,
      carsAllowedPerBranch: 20,
      driversAllowedPerBranch: 10,
      branchesAllowed: 5,
      primaryContactAndCompanyManagerSame: "Y",
    },
    {
      id: "1113",
      companyName: "ABC Hospital",
      typeOfCompany: "Hospital",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Inactive",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "RTGS",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales Person Name",
      salesPersonId: "SP123",
      carsPermittedPerDay: 50,
      packageType: "Standard",
      driversAllowed: 100,
      carsAllowedPerBranch: 20,
      driversAllowedPerBranch: 10,
      branchesAllowed: 5,
      primaryContactAndCompanyManagerSame: "Y",
    },
    {
      id: "1114",
      companyName: "City Mall",
      typeOfCompany: "Mall",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Active",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "RTGS",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales Person Name",
      salesPersonId: "SP123",
      carsPermittedPerDay: 50,
      packageType: "Standard",
      driversAllowed: 100,
      carsAllowedPerBranch: 20,
      driversAllowedPerBranch: 10,
      branchesAllowed: 5,
      primaryContactAndCompanyManagerSame: "Y",
    },
    {
      id: "1115",
      companyName: "Train Station",
      typeOfCompany: "Railway Station",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Active",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "Cheque",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales Person Name",
      salesPersonId: "SP123",
      carsPermittedPerDay: 50,
      packageType: "Standard",
      driversAllowed: 100,
      carsAllowedPerBranch: 20,
      driversAllowedPerBranch: 10,
      branchesAllowed: 5,
      primaryContactAndCompanyManagerSame: "Y",
    },
    {
      id: "1116",
      companyName: "Airport Lounge",
      typeOfCompany: "Airport",
      firstLineAddress: "123 Main Street",
      secondLineAddress: "Apt 101",
      city: "Metropolis",
      taluka: "Central",
      district: "Pune",
      state: "Maharashtra",
      countryPinCode: "India, 123456",
      status: "Active",
      contactNumber: "123-456-7890",
      gstNumber: "GST123456789",
      licenseType: "Per car",
      discountType: "10% off",
      rate: "$100",
      primaryContactFirstName: "John",
      primaryContactLastName: "Doe",
      primaryContactNumber: "987-654-3210",
      primaryContactEmail: "john.doe@example.com",
      secondaryContactFirstName: "Jane",
      secondaryContactLastName: "Smith",
      secondaryContactNumber: "567-890-1234",
      secondaryContactEmail: "jane.smith@example.com",
      paymentMethod: "NEFT",
      referralCustomer: "Yes",
      referredBy: "Referrer Name",
      customerAcquisitionMethod: "Referral",
      trialPeriod: "Yes",
      trialDuration: "30 days",
      salesPersonName: "Sales",
    },
  ];

  export default customers;