const customerInformation = {
    // companyName: "JW Marriot",
    // companyType: "Hotel",
    // addressLine1: "123 Main St",
    // addressLine2: "Suite 456",
    // city: "Pune",
    // taluka: "Haveli",
    // district: "Pune",
    // state: "Maharashtra",
    // country: "India",
    // pinCode: "411001",
    // contactNumber: "9876543210",
    // gstNumber: "27AAAPL1234C1ZQ",
    // licenseType: "Per car",
    // discountType: "Seasonal",
    // rate: 10000,
    // primaryContactFirstName: "John",
    // primaryContactLastName: "Doe",
    // primaryContactNumber: "9876543211",
    // primaryContactEmail: "john.doe@example.com",
    // secondaryContactFirstName: "Jane",
    // secondaryContactLastName: "Smith",
    // secondaryContactNumber: "9876543212",
    // secondaryContactEmail: "jane.smith@example.com",
    // paymentMethod: "NEFT",
    // referralCustomer: "Yes",
    // referredBy: "Existing Customer",
    // customerAcquisitionMethod: "referral",
    // isTrialPeriod: "Yes",
    // trialDuration: "30 days",
    // salesPersonName: "Michael",
    // salesPersonID: "SP12345",
    // totalCarsPermittedPerDay: 50,
    // packageType: "Premium",
    // totalDriversAllowed: 20,
    // carsAllowedPerBranch: 10,
    // driversAllowedPerBranch: 5,
    // numberOfBranchesAllowed: 5,
    // primaryContactAndManagerSame: "No"
  };

  export default customerInformation;